services:
  # PostgreSQL Database (Internal Only)
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: easydoc_database2
      POSTGRES_USER: easydoc_database2_user
      POSTGRES_PASSWORD: docker_secure_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    # Remove external port exposure - database only accessible within Docker network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d
    networks:
      - easydoc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U easydoc_database2_user -d easydoc_database2"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Node.js Backend Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easydoc-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://easydoc_database2_user:docker_secure_password_2024@postgres:5432/easydoc_database2?schema=public&connect_timeout=300
      JWT_SECRET: docker_jwt_secret_key_2024_easydoc_secure
      PORT: 3001
      CORS_ORIGINS: https://esdkku.vercel.app,http://localhost:3001,http://headquarters.thddns.net:9553,http://10.0.0.20:3001
      FIREBASE_STORAGE_BUCKET: easydocv1.appspot.com
      GOOGLE_APPLICATION_CREDENTIALS: /app/src/config/easydocv1-firebase-adminsdk-r4zkx-e42d3aabbc.json
      FIREBASE_SA_BASE64: ${FIREBASE_SA_BASE64}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - easydoc-network
    command: >
      sh -c '
        mkdir -p /app/src/config &&
        printf "%s" "$FIREBASE_SA_BASE64" | base64 -d > /app/src/config/easydocv1-firebase-adminsdk-r4zkx-e42d3aabbc.json &&
        node src/index.js
      '

volumes:
  postgres_data:
    driver: local

networks:
  easydoc-network:
    driver: bridge
