import type { Metadata } from "next";
import "./globals.css";
import Loader from "@/components/Loader/Loader";
import { ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html>
      <meta name="format-detection" content="telephone=no,email=no,address=no,date=no"></meta>
      <body>
        <Loader />
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
